### ISSUE TITLE
AttributeError: 'map' object has no attribute 'count'

### ISSUE THREAD

**Issue by Chinna111** [AlexPnt/Default-Credit-Card-Prediction#1]
How should I fix this.

    positive_counts=[0]*len(index)
    negative_counts=[0]*len(index)
    for v in range(len(unique_values)):
        positive_counts[v]=positive_values.count(v)/n_positive_labels
        negative_counts[v]=negative_values.count(v)/n_negative_labels

it will show like this:
AttributeError: 'map' object has no attribute 'count'

**Comment by alexpnt** [comment]
What python version are you using?
Recall that this project was developed under Python 2.x
